// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-auth_LoginData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.Response-auth_UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            }
        },
        "/questions/{qid}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Update question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "qid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/question.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-question_Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Delete question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Question ID (UUID)",
                        "name": "qid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_MessageData"
                        }
                    }
                }
            }
        },
        "/quizzes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quizzes"
                ],
                "summary": "List quizzes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_ListData-quiz_QuizResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quizzes"
                ],
                "summary": "Create quiz",
                "parameters": [
                    {
                        "description": "Quiz data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/quiz.CreateQuizRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.Response-quiz_QuizResponse"
                        }
                    }
                }
            }
        },
        "/quizzes/join/{code}": {
            "get": {
                "tags": [
                    "quizzes"
                ],
                "summary": "Join quiz by code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-quiz_QuizJoinData"
                        }
                    }
                }
            }
        },
        "/quizzes/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "quizzes"
                ],
                "summary": "Get quiz by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-quiz_QuizResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorBody"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "quizzes"
                ],
                "summary": "Update quiz",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Quiz update data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/quiz.UpdateQuizRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-quiz_QuizResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "quizzes"
                ],
                "summary": "Delete quiz",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_MessageData"
                        }
                    }
                }
            }
        },
        "/quizzes/{id}/finish": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "quizzes"
                ],
                "summary": "Finish quiz",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-quiz_QuizFinishData"
                        }
                    }
                }
            }
        },
        "/quizzes/{id}/questions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "questions"
                ],
                "summary": "List questions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_ListData-question_Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "questions"
                ],
                "summary": "Create question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Question data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/question.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.Response-question_Response"
                        }
                    }
                }
            }
        },
        "/quizzes/{id}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "quizzes"
                ],
                "summary": "Start quiz",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-quiz_QuizStartData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/auth.UserResponse"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "question.CreateRequest": {
            "type": "object",
            "required": [
                "options",
                "text"
            ],
            "properties": {
                "correct_idx": {
                    "type": "integer",
                    "minimum": 0
                },
                "options": {
                    "type": "array",
                    "minItems": 2,
                    "items": {
                        "type": "string"
                    }
                },
                "order_num": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "question.Response": {
            "type": "object",
            "properties": {
                "correct_idx": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "order_num": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                },
                "quiz_id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "quiz.CreateQuizRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "time_per_question": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "quiz.QuizFinishData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/quiz.ResultResponse"
                    }
                }
            }
        },
        "quiz.QuizJoinData": {
            "type": "object",
            "properties": {
                "quiz_code": {
                    "type": "string"
                },
                "quiz_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "quiz.QuizResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "quiz_code": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "time_per_question": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "quiz.QuizStartData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "quiz_code": {
                    "type": "string"
                }
            }
        },
        "quiz.ResultResponse": {
            "type": "object",
            "properties": {
                "rank": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "quiz.UpdateQuizRequest": {
            "type": "object",
            "properties": {
                "time_per_question": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.ErrorBody": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.ListData-question_Response": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/question.Response"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.ListData-quiz_QuizResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/quiz.QuizResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.MessageData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.Response-auth_LoginData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.LoginData"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Response-auth_UserResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.UserResponse"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Response-question_Response": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/question.Response"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Response-quiz_QuizFinishData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/quiz.QuizFinishData"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Response-quiz_QuizJoinData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/quiz.QuizJoinData"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Response-quiz_QuizResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/quiz.QuizResponse"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Response-quiz_QuizStartData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/quiz.QuizStartData"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Response-response_ListData-question_Response": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.ListData-question_Response"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Response-response_ListData-quiz_QuizResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.ListData-quiz_QuizResponse"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Response-response_MessageData": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.MessageData"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Quiz Platform API",
	Description:      "Real-time quiz platform with live leaderboards.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
